apiVersion: apps/v1
kind: Deployment
metadata:
  name: roman-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: devops2022.azurecr.io/romanginx:fc285c5b6ee3cb1b2879d33b25f61d4d967dbf5e
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: roman-nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roman-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #kubernetes.io/ingress.class: "nginx"
    #kubernetes.io/ingress.allow-http: "true"
    #cert-manager.io/cluster-issuer: certmanager_name
spec:
  #tls:
  #- hosts:
  #  - devops2022.de
  #  secretName: secret
  rules:
    - host: devops2022.de
      http:
        paths:
          - path: /roman
            pathType: Prefix
            backend:
              service:
                name: roman-service
                port:
                  number: 80
