apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: devops2022.azurecr.io/simonnginx:2c29573ccfe8a8aa910f6c0ea11ce5283bb9d400
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simon-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simon-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.devops2022.de
      http:
        paths:
          - path: /simon
            backend:
              serviceName: simon-service
              servicePort: 80
